added qemu to cloudinit
whiteducksoftware/azure-devops-build-agent pull request #24
Opened 2020-11-06 16:13 UTC by dariobro

2020-11-06 16:17 UTC, dariobro commented
testen werde ich das dann in der alten preview offer vom pro v2

2020-11-06 16:38 UTC, StiviiK commented
Du hast das Installieren der Pakete vergessen: `qemu-user-static`, `binfmt-support`

2020-11-06 16:39 UTC, StiviiK requested changes

2020-11-06 16:39 UTC, StiviiK commented on infrastructure/scripts/cloud-init.yml
> +  - apt-get install -y docker-ce=5:19.03.10~3-0~ubuntu-bionic docker-ce-cli=5:19.03.10~3-0~ubuntu-bionic containerd.io=1.2.13-2
Du hast das Installieren der Pakete vergessen: qemu-user-static, binfmt-support

2020-11-06 16:48 UTC, dariobro commented on infrastructure/scripts/cloud-init.yml
> +  - apt-get install -y docker-ce=5:19.03.10~3-0~ubuntu-bionic docker-ce-cli=5:19.03.10~3-0~ubuntu-bionic containerd.io=1.2.13-2
Zeile 9 und 10

2020-11-06 16:50 UTC, StiviiK commented on infrastructure/scripts/cloud-init.yml
> +  - apt-get install -y docker-ce=5:19.03.10~3-0~ubuntu-bionic docker-ce-cli=5:19.03.10~3-0~ubuntu-bionic containerd.io=1.2.13-2
Du hast recht das habe ich übersehen 👍🏽

2020-11-15 12:21 UTC, nmeisenzahl commented
Fixes #27

2020-11-16 15:36 UTC, dariobro commented
indentation in mainTemplate.json fixen

2020-11-16 15:50 UTC, StiviiK approved these changes

2020-11-16 15:51 UTC, merged